parameters:
  name: 'build'
  configuration: 'Debug' # 'Debug' or 'Release'
  tag: false # true if the source needs to be tagged
  publish: false # true if artifacts need to be published
  dependsOn: []

stages:
- stage: '${{ parameters.name }}'

  variables:
    artifactName: 'Solutions'
    artifactPath: 'bin\${{ parameters.configuration }}\Solutions.zip'

  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: '${{ parameters.name }}_job'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      persistCredentials: true
    - task: Npm@1
      displayName: "Run 'npm install'"
      inputs:
        command: 'install'
        workingDir: 'src\'
    - task: VSBuild@1
      displayName: "Build"
      inputs:
        solution: 'src\Solutions\Solutions.cdsproj'
        msbuildArgs: '/t:build /p:configuration=${{ parameters.configuration }} /restore'
    - powershell: |
        echo "Tagging Build: $($env:BUILD_NUMBER)"
        git tag $env:BUILD_NUMBER
        git push origin $env:BUILD_NUMBER
      displayName: 'Tag the build'
      env:
        BUILD_NUMBER: $(build.buildNumber)
        GIT_REDIRECT_STDERR: 2>&1
      condition: and(succeeded(), eq(${{ parameters.tag }}, true))
    - publish: '$(artifactPath)'
      displayName: 'Publishing $(artifactName)'
      artifact: '$(artifactName)'
      condition: and(succeeded(), eq(${{ parameters.publish }}, true))
