variables:
  version: '1.2.1'

name: $(version).$(build.buildId)

trigger:
- master

pr:
- master

stages:
- template: templates/stages/build.yml
  parameters:
    name: 'ci_build'
    version: '$(version)'
