name: 1.2.0.$(build.buildId)

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: "build_stage"
  jobs:
  - job: "build_job"
    steps:
    - task: Npm@1
      displayName: "Run 'npm install'"
      inputs:
        command: 'install'
    - task: VSBuild@1
      displayName: "Build"
      inputs:
        solution: 'Solutions\Solutions.cdsproj'
        msbuildArgs: '/t:build /restore'